### ISSUE TITLE
Automatische Erstellung von Zuständen

### ISSUE THREAD

**Issue by duczz** [anwa/ioBroker.tasmota#1]
Alle "Automatische Erstellung von Zuständen" werden erstellt obwohl nicht angehakt 
![image](https://user-images.githubusercontent.com/25475385/105630333-d63e5e80-5e48-11eb-8bd4-d78a2a9688f9.png)

**Comment by anwa** [comment]
Hi @duczz ,
ich habe an der Stelle nichts geändert.
Ich habe mir den Code dazu angesehen, und wahrscheinlich missverstehst du die Funktion.
Im Code wird die Automatische Erstellung nur unterdrückt, wenn der Datenpunkt nicht in der Liste datapoints.js steht.

Siehe hier in server.js:
![Screenshot_20210124_155902](https://user-images.githubusercontent.com/1856906/105634216-3fc86800-5e5d-11eb-9b59-461bb924deb4.png)

Dieser else Part wird nur aufgerufen falls der Datenpunkt nicht gefunden wurde in datapoints.js
So ganz erschließt sich mir der Sinn dahinter aber eh nicht. Ich will doch alle Datenpunkte haben...

**Comment by duczz** [comment]
hm komisch, ist nämlich nur in deinem fork so, im sonoff Adapter werden die nur geladen wenn auch angehakt.
Theoretisch ist mir das ja egal, weil deine Subfolder Struktur die Übersicht eh verbessert, wollte es nur mal erwähnen.

Ansonsten funktioniert alles einwandfrei

**Comment by anwa** [comment]
Welche werden denn angelegt? Sind diese in datapoints.js vorhanden? Ansonsten sollten sie sich gleich verhalten.
Wie gesagt, ich habe das gesamte Projekt nach den TELE_SENSOR durchsucht. Der Code Ausschnitt oben ist das einzige Vorkommen...
Oder was würdest du von der Funktion erwarten?

**Comment by duczz** [comment]
Sorry, aber was ist die datapoint.js und wo find ich die?
Naja, im Sonoff Adapter hab ich nur Sensoren aktiviert, da mich z.b. WIFI SSID etc. nicht interessiert, durch die subfolder funktion, könnte man die in der gui aber auch komplett entfernen

Sonoff Adapter:
![image](https://user-images.githubusercontent.com/25475385/105634965-e6623800-5e60-11eb-87ae-12f2f437e352.png)

Dein Adapter:
![image](https://user-images.githubusercontent.com/25475385/105634974-f11ccd00-5e60-11eb-89b9-924a535e2742.png)

**Comment by anwa** [comment]
Also, ich habe das Verhalten nochmal genauer überprüft, und es macht (bei mir) genau das was im Code auch steht!

Ich habe folgendes gemacht:
- Adapter gestoppt
- die drei Haken rausgenommen
- in Objekte 'Tasmota.0' gelöscht
- Adapter über Git upgedatet
- Adapter wieder gestartet

Alles wie erwartet, nur die Datenpunkte die in [Datapoints](lib/datapoints.js) stehen werden erstellt.

![Screenshot_20210125_071901](https://user-images.githubusercontent.com/1856906/105668485-b0af6480-5edd-11eb-8256-00b885a116fe.png)

**Comment by anwa** [comment]
So sieht mein Shelly nur mit TELE_SENSOR aktiviert aus:
![Screenshot_20210125_074104](https://user-images.githubusercontent.com/1856906/105670251-033e5000-5ee1-11eb-9098-3576d5c52c89.png)
Und so, wenn alle angewählt sind:
![Screenshot_20210125_074215](https://user-images.githubusercontent.com/1856906/105670290-16512000-5ee1-11eb-9398-8233040199de.png)

**Comment by duczz** [comment]
@anwa Ich hab nun den tasmota Objektbaum gelöscht und das aktuell Release gezogen jetzt passt es - Strange.

Dann funktiont dein Release nun perfekt, vielen Dank für deine Mühe 👍🏻
