### ISSUE TITLE
IP Adresse fehlt

### ISSUE THREAD

**Issue by duczz** [anwa/ioBroker.tasmota#2]
Mit der neuen Baumstruktur wird mir die IP nicht mehr mit angezeigt, weißt du ggf warum?
![image](https://user-images.githubusercontent.com/25475385/108684979-dbe49e00-74f3-11eb-8d4a-1a367e7873e4.png)

**Comment by anwa** [comment]
Die IP wird beim Starten von Tasmota einmalig in den INFO Telegrammen versendet.
![Screenshot_20210222_095623](https://user-images.githubusercontent.com/1856906/108685406-662d0200-74f4-11eb-95fa-1134a44e6f03.png)
Also Versuch mal reset in Tasmota. Ausserdem habe ich in ioBroker öfter das Problem, das States nicht aktualisiert werden.
Klick doch mal im Objektbaum auf 'Baum neu erstellen' und zusätzlich refresch die Seite im Browser.

**Comment by duczz** [comment]
Danke, der Reboot wars :)
